language: perl
perl:
- "5.18"
- "5.16"
- "5.14"
- "5.12"

before_install:
- git config --global user.name "TravisCI"

install:
- cpanm --quiet --notest --skip-satisfied Dist::Zilla
- dzil authordeps --missing | grep --invert-match --perl-regex '[^\w:]' | cpanm --quiet --notest --skip-satisfied
- dzil listdeps --author --missing | grep --invert-match --perl-regex '[^\w:]' | cpanm --quiet --notest --skip-satisfied

script:
- dzil smoke --release --author
