---
abstract: 'remove clutter from your news feeds'
author:
  - 'Daniel Holz <dgholz@gmail.com>'
build_requires:
  File::Temp: 0
  Mojo::Message::Response: 0
  Mojo::Transaction: 0
  Moose: 0
  Test::Exception: 0
  Test::MockObject: 0
  Test::More: 0
  Test::Most: 0
  Test::Routine: 0
  Test::Routine::Util: 0
  namespace::autoclean: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Rssfilter
requires:
  App::Cmd::Setup: 0
  Class::Inspector: 0
  Cwd: 0
  HTTP::Date: 0
  List::MoreUtils: 0
  List::Util: 0
  Log::Any: 0
  Log::Any::Adapter: 0
  Method::Signatures: 0
  Module::Runtime: 0
  Mojo::DOM: 0
  Mojo::UserAgent: 0
  Mojolicious: 3.28
  Moo: 0
  Moo::Role: 0
  Path::Class: 0
  Path::Class::Dir: 0
  Path::Class::File: 0.26
  Scalar::Util: 0
  Try::Tiny: 0
  YAML::XS: 0
  constant: 0
  feature: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dgholz/App-Rssfilter/issues
  homepage: https://github.com/dgholz/App-Rssfilter
  repository: https://github.com/dgholz/App-Rssfilter.git
version: 0.03
